spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/My-Realm/protocol/openid-connect/certs


server:
  port: 9191
  
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

# Enable this for debugging
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
