eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 0
spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8888
    vault:
      application-name: product-service
      authentication: TOKEN
      host: localhost
      port: 8200
      scheme: http
      token: s.wf7sYy2miRryGj5RFU45r1Sf
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
